<?php

namespace Database\Seeders;

use App\Models\Employee;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class EmployeeSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        Employee::insert([
            [
                'id' => 'ec9fb2c6-a118-4748-91be-804d9b6ae87b',
                'employee_status_id' => 1,
                'employee_type_id' => 7,
                'university_id' => null,
                'scientific_field_id' => 7,
                'religion_id' => 1,
                // 'homebase_id' => null,
                'nip' => '009993884734',
                'nidn' => '00937738747343',
                'nidk' => null,
                'nupn' => null,
                'nbm' => null,
                'name' => 'Suprapto',
                'front_title' => 'Dr',
                'back_title' => 'S.Kom.,M.Kom',
                'gender' => 'L',
                'birthplace' => 'Banyuwangi',
                'birthdate' => '1987-09-12',
                'phone_number' => '085625615526',
                'personal_email' => 'suprapto@gmail.com',
                'campus_email' => 'suprapto@poliwangi.ac.id',
                'address' => 'Jl. Anggrek No. 34, Banyuwangi',
                'marital_status' => 'M',
                'country_id' => 'ID'
            ],
            [
                'id' => 'ec9fb2c6-a118-4748-91be-804d9b6ae81b',
                'employee_status_id' => 1,
                'employee_type_id' => 7,
                'university_id' => null,
                'scientific_field_id' => 7,
                'religion_id' => 1,
                // 'homebase_id' => null,
                'nip' => '099188273677',
                'nidn' => '091883774627367',
                'nidk' => null,
                'nupn' => null,
                'nbm' => null,
                'name' => 'Sindy Rahayu',
                'front_title' => null,
                'back_title' => 'S.T.,M.T',
                'gender' => 'P',
                'birthplace' => 'Banyuwangi',
                'birthdate' => '1990-09-12',
                'phone_number' => '085625615527',
                'personal_email' => 'sindy@gmail.com',
                'campus_email' => 'sindy@poliwangi.ac.id',
                'address' => 'Jl. Bomo, Karangrejo, Blimbingsari',
                'marital_status' => 'M',
                'country_id' => 'ID'
            ],
            [
                'id' => '83ec3a2d-d4c7-417d-be37-3a494670ce85',
                'employee_status_id' => 1,
                'employee_type_id' => 1,
                'university_id' => null,
                'scientific_field_id' => 5,
                'religion_id' => 1,
                // 'homebase_id' => null,
                'nip' => '993882883923',
                'nidn' => '110009388488934',
                'nidk' => null,
                'nupn' => null,
                'nbm' => null,
                'name' => 'Saiful Bahri',
                'front_title' => null,
                'back_title' => 'S.Pd.,M.Pd',
                'gender' => 'L',
                'birthplace' => 'Malang',
                'birthdate' => '1978-09-12',
                'phone_number' => '085625615528',
                'personal_email' => 'saiful@gmail.com',
                'campus_email' => 'saiful@poliwangi.ac.id',
                'address' => 'Jl. Nasional III, Rogojampi',
                'marital_status' => 'M',
                'country_id' => 'ID'
            ],
            [
                'id' => '83ec3a2d-d4c7-417d-be37-3a494670ce84',
                'employee_status_id' => 1,
                'employee_type_id' => 7,
                'university_id' => null,
                'scientific_field_id' => 7,
                'religion_id' => 1,
                // 'homebase_id' => null,
                'nip' => '883992883748',
                'nidn' => '991883773777132',
                'nidk' => null,
                'nupn' => null,
                'nbm' => null,
                'name' => 'Diana Lestari',
                'front_title' => null,
                'back_title' => 'S.Tr.Kom.,M.T',
                'gender' => 'P',
                'birthplace' => 'Surabaya',
                'birthdate' => '1989-10-09',
                'phone_number' => '085625615529',
                'personal_email' => 'diana@gmail.com',
                'campus_email' => 'diana@poliwangi.ac.id',
                'address' => 'Jl. Kepiting, Banyuwangi',
                'marital_status' => 'M',
                'country_id' => 'ID'
            ],
            [
                'id' => '83ec3a2d-d4c7-417d-be37-3a494670ce87',
                'employee_status_id' => 1,
                'employee_type_id' => 7,
                'university_id' => null,
                'scientific_field_id' => 7,
                'religion_id' => 1,
                // 'homebase_id' => null,
                'nip' => '098883874734',
                'nidn' => '111092830001029',
                'nidk' => null,
                'nupn' => null,
                'nbm' => null,
                'name' => 'Rio Ardiansyah',
                'front_title' => null,
                'back_title' => 'S.Pd.,M.T',
                'gender' => 'L',
                'birthplace' => 'Banyuwangi',
                'birthdate' => '1979-10-09',
                'phone_number' => '085625615510',
                'personal_email' => 'rio@gmail.com',
                'campus_email' => 'rio@poliwangi.ac.id',
                'address' => 'Jl. Kepiting, Banyuwangi',
                'marital_status' => 'M',
                'country_id' => 'ID'
            ],
            [
                'id' => '83ec3a2d-d4c7-417d-be37-3a494670ce89',
                'employee_status_id' => 1,
                'employee_type_id' => 7,
                'university_id' => null,
                'scientific_field_id' => 7,
                'religion_id' => 1,
                // 'homebase_id' => null,
                'nip' => '197601222021211001',
                'nidn' => '722017601',
                'nidk' => null,
                'nupn' => null,
                'nbm' => null,
                'name' => 'Mohamad Dimyati Ayatullah',
                'front_title' => null,
                'back_title' => 'S.T.,M.Kom',
                'gender' => 'L',
                'birthplace' => 'Banyuwangi',
                'birthdate' => '1976-01-22',
                'phone_number' => '085625615511',
                'personal_email' => 'dimyati@gmail.com',
                'campus_email' => 'dimyati@poliwangi.ac.id',
                'address' => 'Sumbersari, Srono',
                'marital_status' => 'M',
                'country_id' => 'ID'
            ],
            [
                'id' => '83ec3a2d-d4c7-417d-be37-3a494670ce81',
                'employee_status_id' => 1,
                'employee_type_id' => 7,
                'university_id' => null,
                'scientific_field_id' => 7,
                'religion_id' => 1,
                // 'homebase_id' => null,
                'nip' => '198403052021212004',
                'nidn' => '705038402',
                'nidk' => null,
                'nupn' => null,
                'nbm' => null,
                'name' => 'Dianni Yusuf',
                'front_title' => null,
                'back_title' => 'S.Kom.,M.Kom',
                'gender' => 'L',
                'birthplace' => 'Banyuwangi',
                'birthdate' => '1984-03-05',
                'phone_number' => '085625615512',
                'personal_email' => 'dianiyusuf@gmail.com',
                'campus_email' => 'dianiyusuf@poliwangi.ac.id',
                'address' => 'Purwodadi, Gambiran',
                'marital_status' => 'M',
                'country_id' => 'ID'
            ],
            [
                'id' => '83ec3a2d-d4c7-417d-be37-3a494670ce82',
                'employee_status_id' => 1,
                'employee_type_id' => 7,
                'university_id' => null,
                'scientific_field_id' => 7,
                'religion_id' => 1,
                // 'homebase_id' => null,
                'nip' => '197806132014041001',
                'nidn' => '713067802',
                'nidk' => null,
                'nupn' => null,
                'nbm' => null,
                'name' => 'Muh. Fuad Al Haris',
                'front_title' => null,
                'back_title' => 'S.T.,M.T',
                'gender' => 'L',
                'birthplace' => 'Banyuwangi',
                'birthdate' => '1978-06-13',
                'phone_number' => '085625615513',
                'personal_email' => 'fuad@gmail.com',
                'campus_email' => 'fuad@poliwangi.ac.id',
                'address' => 'Lateng, Banyuwangi',
                'marital_status' => 'M',
                'country_id' => 'ID'
            ],
            [
                'id' => '83ec3a2d-d4c7-417d-be37-3a494670ce83',
                'employee_status_id' => 1,
                'employee_type_id' => 7,
                'university_id' => null,
                'scientific_field_id' => 1,
                'religion_id' => 1,
                // 'homebase_id' => null,
                'nip' => '197108272021211002',
                'nidn' => '727087102',
                'nidk' => null,
                'nupn' => null,
                'nbm' => null,
                'name' => 'Enes Ariyanto Sandi',
                'front_title' => null,
                'back_title' => 'S.T.,M.M',
                'gender' => 'L',
                'birthplace' => 'Surabaya',
                'birthdate' => '1971-08-27',
                'phone_number' => '085625615513',
                'personal_email' => 'enes@gmail.com',
                'campus_email' => 'enes@poliwangi.ac.id',
                'address' => 'Penataban, Giri',
                'marital_status' => 'M',
                'country_id' => 'ID'
            ],
            [
                'id' => '83ec3a2d-d4c7-417d-be37-3a494670ce80',
                'employee_status_id' => 1,
                'employee_type_id' => 7,
                'university_id' => null,
                'scientific_field_id' => 1,
                'religion_id' => 1,
                // 'homebase_id' => null,
                'nip' => '198505172015041003',
                'nidn' => '717058503',
                'nidk' => null,
                'nupn' => null,
                'nbm' => null,
                'name' => 'Zulis Erwanto',
                'front_title' => null,
                'back_title' => 'S.T.,M.T',
                'gender' => 'L',
                'birthplace' => 'Lamongan',
                'birthdate' => '1985-05-17',
                'phone_number' => '085625615514',
                'personal_email' => 'zulis@gmail.com',
                'campus_email' => 'zulis@poliwangi.ac.id',
                'address' => 'Sobo, Banyuwangi',
                'marital_status' => 'M',
                'country_id' => 'ID'
            ],
            [
                'id' => '83ec3a2d-d4c7-417d-be37-3a494670ce12',
                'employee_status_id' => 1,
                'employee_type_id' => 7,
                'university_id' => null,
                'scientific_field_id' => 1,
                'religion_id' => 1,
                // 'homebase_id' => null,
                'nip' => '198605212015041002',
                'nidn' => '21058606',
                'nidk' => null,
                'nupn' => null,
                'nbm' => null,
                'name' => 'M. Shofi\'ul Amin',
                'front_title' => null,
                'back_title' => 'S.T.,M.T',
                'gender' => 'L',
                'birthplace' => 'Kediri',
                'birthdate' => '1986-05-21',
                'phone_number' => '082336056463',
                'personal_email' => 'sofi@gmail.com',
                'campus_email' => 'sofi@poliwangi.ac.id',
                'address' => 'Pancoran, Kediri',
                'marital_status' => 'M',
                'country_id' => 'ID'
            ],
            [
                'id' => '83ec3a2d-d4c7-417d-be37-3a494670ce09',
                'employee_status_id' => 1,
                'employee_type_id' => 7,
                'university_id' => null,
                'scientific_field_id' => 1,
                'religion_id' => 1,
                // 'homebase_id' => null,
                'nip' => '198311052015041001',
                'nidn' => '705118304',
                'nidk' => null,
                'nupn' => null,
                'nbm' => null,
                'name' => 'Devit Suwardiyanto',
                'front_title' => null,
                'back_title' => 'S.Si.,M.T',
                'gender' => 'L',
                'birthplace' => 'Malang',
                'birthdate' => '1983-11-05',
                'phone_number' => '082336056464',
                'personal_email' => 'devit@gmail.com',
                'campus_email' => 'devit@poliwangi.ac.id',
                'address' => 'Genteng Wetan, Genteng',
                'marital_status' => 'M',
                'country_id' => 'ID'
            ],
            [
                'id' => '83ec3a2d-d4c7-417d-be37-3a494670ce98',
                'employee_status_id' => 1,
                'employee_type_id' => 7,
                'university_id' => null,
                'scientific_field_id' => 1,
                'religion_id' => 1,
                // 'homebase_id' => null,
                'nip' => '198804042018031001',
                'nidn' => '4048802',
                'nidk' => null,
                'nupn' => null,
                'nbm' => null,
                'name' => 'Kurniawan Muhammad Nur',
                'front_title' => null,
                'back_title' => 'S.ST.,M.M',
                'gender' => 'L',
                'birthplace' => 'Jember',
                'birthdate' => '1988-04-04',
                'phone_number' => '082336056465',
                'personal_email' => 'kurniawan@gmail.com',
                'campus_email' => 'kurniawan@poliwangi.ac.id',
                'address' => 'Dadapan, Banyuwangi',
                'marital_status' => 'M',
                'country_id' => 'ID'
            ],
            [
                'id' => '83ec3a2d-d4c7-417d-be37-3a494670ce14',
                'employee_status_id' => 1,
                'employee_type_id' => 7,
                'university_id' => null,
                'scientific_field_id' => 1,
                'religion_id' => 1,
                // 'homebase_id' => null,
                'nip' => '198304132021211003',
                'nidn' => '713048303',
                'nidk' => null,
                'nupn' => null,
                'nbm' => null,
                'name' => 'Abdul Rohman',
                'front_title' => null,
                'back_title' => 'ST.,MT',
                'gender' => 'L',
                'birthplace' => 'Banyuwangi',
                'birthdate' => '1983-04-13',
                'phone_number' => '085259505795',
                'personal_email' => 'rohman@gmail.com',
                'campus_email' => 'rohman@poliwangi.ac.id',
                'address' => 'Sumberejo, Banyuwangi',
                'marital_status' => 'M',
                'country_id' => 'ID'
            ],
            [
                'id' => '83ec3a2d-d4c7-417d-be37-3a494670ce76',
                'employee_status_id' => 1,
                'employee_type_id' => 7,
                'university_id' => null,
                'scientific_field_id' => 1,
                'religion_id' => 1,
                // 'homebase_id' => null,
                'nip' => '197704042021211004',
                'nidn' => '4047712',
                'nidk' => null,
                'nupn' => null,
                'nbm' => null,
                'name' => 'Dedy Hidayat Kusuma',
                'front_title' => null,
                'back_title' => 'S.T.,M.Cs',
                'gender' => 'L',
                'birthplace' => 'Banyuwangi',
                'birthdate' => '1977-04-04',
                'phone_number' => '081331983392',
                'personal_email' => 'dedy@gmail.com',
                'campus_email' => 'dedy@poliwangi.ac.id',
                'address' => 'Kedungwungu, Tegaldelimo',
                'marital_status' => 'M',
                'country_id' => 'ID'
            ],
        ]);
    }
}
