<?php

namespace Database\Seeders;

use App\Models\Ethnic;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class EthnicSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        Ethnic::insert([
            ["name" => "Aceh"],
            ["name" => "Alas"],
            ["name" => "Alor"],
            ["name" => "Ambon"],
            ["name" => "Anak dalam"],
            ["name" => "Aneuk Jamee"],
            ["name" => "Arab"],
            ["name" => "Arfak"],
            ["name" => "Asmat"],
            ["name" => "Atoni"],
            ["name" => "Auwye/Mee"],
            ["name" => "Bajao"],
            ["name" => "Bali"],
            ["name" => "Banggai"],
            ["name" => "Banjar"],
            ["name" => "Batak"],
            ["name" => "Bawean"],
            ["name" => "Betawi"],
            ["name" => "Bima"],
            ["name" => "Bugis"],
            ["name" => "Buol"],
            ["name" => "Buton"],
            ["name" => "Dani"],
            ["name" => "Dauwa"],
            ["name" => "Dayak"],
            ["name" => "Devayan"],
            ["name" => "Dompu"],
            ["name" => "Duano"],
            ["name" => "Duri"],
            ["name" => "Flores"],
            ["name" => "Galela"],
            ["name" => "Gayo"],
            ["name" => "Gorontalo"],
            ["name" => "India"],
            ["name" => "Jawa"],
            ["name" => "Kaili"],
            ["name" => "Karo"],
            ["name" => "Kei"],
            ["name" => "Keturunan Belanda- Portugis"],
            ["name" => "Keturunan Jepang"],
            ["name" => "Kluet"],
            ["name" => "Komering"],
            ["name" => "Kutai"],
            ["name" => "Lamaholot"],
            ["name" => "Lampung"],
            ["name" => "Lauje"],
            ["name" => "Lio"],
            ["name" => "Lombok"],
            ["name" => "Lubu"],
            ["name" => "Luwu"],
            ["name" => "Madura"],
            ["name" => "Makassar"],
            ["name" => "Makian"],
            ["name" => "Mamasa"],
            ["name" => "Mamuju"],
            ["name" => "Mandar"],
            ["name" => "Manggarai"],
            ["name" => "Mbojo"],
            ["name" => "Melayu"],
            ["name" => "Mentawai"],
            ["name" => "Minahasa (Manado)"],
            ["name" => "Minangkabau"],
            ["name" => "Mongondow"],
            ["name" => "Moni"],
            ["name" => "Mukomuko"],
            ["name" => "Muna"],
            ["name" => "Ngada"],
            ["name" => "Ngalik"],
            ["name" => "Nias"],
            ["name" => "Pakistani/Punjab"],
            ["name" => "Pamona"],
            ["name" => "Pekal"],
            ["name" => "Petalangan"],
            ["name" => "Rejang"],
            ["name" => "Rote"],
            ["name" => "Saluan"],
            ["name" => "Sangir"],
            ["name" => "Saparua"],
            ["name" => "Sawu"],
            ["name" => "Selayar"],
            ["name" => "Seram"],
            ["name" => "Singkil"],
            ["name" => "Sula"],
            ["name" => "Sumba"],
            ["name" => "Sumbawa"],
            ["name" => "Sunda"],
            ["name" => "Talang Mamak"],
            ["name" => "Talaud"],
            ["name" => "Tanimbar"],
            ["name" => "Ternate"],
            ["name" => "Tidore"],
            ["name" => "Tidung"],
            ["name" => "Timor"],
            ["name" => "Tionghoa"],
            ["name" => "Tobelo"],
            ["name" => "Tolaki"],
            ["name" => "Tomini"],
            ["name" => "Toraja"],
            ["name" => "Yapen"]
        ]);
    }
}
